### ISSUE TITLE
Lỗi chức năng Thêm ảnh vào album

### ISSUE THREAD

**Issue by 20127037** [20127037/Usege-Frontend#14]
### Mô tả tình huống
**Bước 1**. Chọn 1 ảnh và dùng chức năng Tạo mới album ```Album1``` (do lúc này chưa có album nào) -> Ảnh xuất hiện trong album (_Test passed_)
**Bước 2**. Chọn 1 ảnh khác và dùng chức năng Tạo mới album ```Album2``` ->```Album2``` chứa luôn những ảnh của  ```Album1``` (_Test failed_)

**Comment by Minhnhat1104** [comment]
fix done
