### ISSUE TITLE
Thư viện không cập nhật ngay lập tức sau khi bấm thêm ảnh

### ISSUE THREAD

**Issue by 20127037** [20127037/Usege-Frontend#5]
### Mô tả tình huống
Trước tiên, mình thêm boolean variable sau để check xem người dùng đã filter hay chưa:
```
private Boolean filtered = false;
```
Tránh mất dữ liệu gốc của ```imgList```, mình đã tạo thêm một bản sao cho nó:
```
List<Image> clonedImgList = new ArrayList<>();
```
Khi hàm ```updateViewDisplay()``` được gọi, mình thêm dòng sau để sao chép toàn bộ dữ liệu của ```imgList``` vào ```clonedImgList``` trong trường hợp người dùng chưa thực hiện filter:
```
if (!filtered) clonedImgList = new ArrayList<>(imgList);
```
Và khởi tạo Fragment với ```clonedImgList```:
```
ft = getSupportFragmentManager().beginTransaction();
imageCardFragment = ImageCardFragment.newInstance(clonedImgList);
ft.replace(R.id.layout_display_images, imageCardFragment).commit();
```
### Vấn đề
Không tính đến hành động filter, tức là giữ nguyên ```filtered = false```, hình ảnh đầu tiên cho app được lấy và hiển thị được lên màn hình. Tuy vậy, khi chọn hình ảnh thứ hai, màn hình không cập nhật liền mà phải thực hiện thêm một thao tác nút khác, ví dụ như bấm vào biểu tượng Card view hoặc List view

**Comment by nguyenthienphu1206** [comment]
imageCardFragment.rcvPhoto.setAdapter(new RecycleAdapter(clonedImgList, imageCardFragment.getContext(), "card"));
